spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=turtle
#spring.data.mongodb.username=
#spring.data.mongodb.password=


spring.datasource.url=jdbc:h2:mem:turtles;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=""
spring.jpa.hibernate.ddl-auto=create-drop